#!/bin/bash
# Cache builders self-management cheat sheet
# Run: bash cache_self_management.sh
# Or source it and use the functions.

echo "=== TM Trading v7.3 Cache Builders - Self Management Commands ==="
echo "Builders are launched with nohup + setsid -f so they survive SSH disconnect / internet drop / logout."
echo "The actual python jobs keep running and writing logs/ even if this terminal or Grok session dies."
echo ""

echo "1. See all running cache builders (including wrappers):"
echo "   ps aux | grep -E '[.]venv/bin/python.*cache_indicators.py' | grep -v grep"
echo ""

echo "2. Count heavy workers (>90% CPU) and total:"
echo "   ps aux | grep -E '[.]venv/bin/python.*cache_indicators.py' | grep -v grep | awk '\$3 > 90 {c++} END {print c+0, \"heavy\"}'"
echo "   ps aux | grep -E '[.]venv/bin/python.*cache_indicators.py' | grep -v grep | wc -l"
echo ""

echo "3. Check critical 2021-12 (the backtest blocker):"
echo "   ps -ef | grep -E 'cache_indicators.*2021-12' | grep -v grep"
echo "   ls -l logs/cache_2021-12.log"
echo "   tail -n 20 logs/cache_2021-12.log"
echo "   tail -f logs/cache_2021-12.log     # (run in its own terminal)"
echo ""

echo "4. Your own persistent temperature monitor (run this before you disconnect - it will keep logging even after you leave):"
echo "   nohup bash -c '"
echo "     while true; do"
echo "       echo \"=== \$(date) ===\""
echo "       sensors 2>/dev/null | grep -E \"Package id [01]:|Core [0-9]:\""
echo "       nvidia-smi -q -d TEMPERATURE 2>/dev/null | grep -E \"GPU [0-9]|Current Temp\""
echo "       sleep 60"
echo "     done >> logs/my_temp_monitor.log 2>&1"
echo "   ' &"
echo "   echo \"My temp monitor started. Check: tail -f logs/my_temp_monitor.log\""
echo ""

echo "5. Tail any log yourself (use separate terminal or tmux/screen if you have it):"
echo "   tail -f logs/cache_2021-12.log"
echo "   tail -f logs/v73_backtest_6y_full.log"
echo "   tail -n 100 -f logs/cache_2023-03.log   # for one of the big ones"
echo ""

echo "6. See backtest progress:"
echo "   tail -n 10 logs/v73_backtest_6y_full.log"
echo "   grep -E 'cache-wait|Wrote report|Processed archive' logs/v73_backtest_6y_full.log | tail -5"
echo ""

echo "7. Find any dead builders (missing parquet but no process running - orphans):"
echo "   python3 -c '"
echo "import os, subprocess, glob"
echo "src = \"data/raw/binance/spot/aggTrades/BTCUSDT/2020-05-22_to_2026-05-21\""
echo "cache = \"results/indicator_cache\""
echo "orphans = []"
echo "for z in sorted(glob.glob(f\"{src}/BTCUSDT-aggTrades-*.zip\")):"
echo "    base = os.path.basename(z)"
echo "    if not os.path.exists(f\"{cache}/{base}.threshold-300.parquet\"):"
echo "        if not subprocess.run([\"pgrep\", \"-f\", f\"cache_indicators.py.*{base}\"], capture_output=True).stdout.strip():"
echo "            orphans.append(base)"
echo "print(len(orphans), \"orphans:\", orphans[:5] if orphans else \"none\")"
echo "   '"
echo ""

echo "8. Relaunch ONLY ONE specific archive if it died (example for 2021-12 - change the archive name for others):"
echo "   setsid -f bash -c '"
echo "     nohup .venv/bin/python scripts/cache_indicators.py \\"
echo "       --dest data/raw/binance/spot/aggTrades/BTCUSDT/2020-05-22_to_2026-05-21 \\"
echo "       --archive \"BTCUSDT-aggTrades-2021-12.zip\" \\"
echo "       --threshold-btc 300 --progress \\"
echo "       >> logs/cache_2021-12.log 2>&1"
echo "   '"
echo "   echo \"Relaunched 2021-12. Watch: tail -f logs/cache_2021-12.log\""
echo ""

echo "9. List still-missing archives (ones without .parquet yet):"
echo "   comm -23 \\"
echo "     <(ls data/raw/binance/spot/aggTrades/BTCUSDT/2020-05-22_to_2026-05-21/BTCUSDT-aggTrades-*.zip 2>/dev/null | xargs -I{} basename {} | sort) \\"
echo "     <(ls results/indicator_cache/*.threshold-300.parquet 2>/dev/null | sed 's/.threshold-300.parquet\$//' | xargs -I{} basename {} | sort)"
echo ""

echo "10. Quick health: which logs have recent 'Processed' activity:"
echo "    grep -l 'Processed .* rows' logs/cache_*.log | wc -l"
echo "    ls -lt logs/cache_*.log | head -10"
echo ""

echo "=== Tips ==="
echo "- Use tmux or screen if available: tmux new -s caches ; then run tails in panes."
echo "- When you SSH back in later: the python jobs will still be running (check with ps)."
echo "- Logs grow only when the python flushes (every 5M rows for 'Processed', or on finish for 'Wrote')."
echo "- Temps are safe as long as Package 1 stays under ~70-75°C (we are at 53-54°C with 35 builders)."
echo "- The backtest will automatically pick up 2021-12 when its .parquet appears (it polls every 10m)."
echo ""
echo "Current snapshot (as of last check): 35 heavy builders, 2021-12 at 5M rows, backtest waiting at ~40m on 2021-12, 99 done / 31 Wrote, load ~35, temps 54C safe."
echo ""
echo "11. NEW: Auto manager for 'make more builders when some finish / heal dead ones':"
echo "    (Updated for 28+ builders: default max now 32. Supports ramping by launching secondary thresholds e.g. 100/200 on remaining or completed archives.)"
echo "    The script scripts/ensure_cache_builders.sh runs in background (started via setsid)."
echo "    It polls every ~25s, launches up to --max concurrent for any missing archives that lack a builder proc."
echo "    This implements dynamic replenishment: as builders finish (freeing a slot) or die, more get started automatically."
echo "    Check it: tail -f logs/cache_manager.log"
echo "    PID: cat logs/cache_manager.pid"
echo "    To stop: kill \$(cat logs/cache_manager.pid)"
echo "    To start manually: setsid -f bash -c 'exec >>logs/cache_manager.log 2>&1; exec bash scripts/ensure_cache_builders.sh --max 16'"
echo "    Builders: fully local/offline (zips + parquet). No net needed after data is here. Survive net drops/logouts."
